<?php
// Include the database connection and data management files
include 'db_connect.php';
include 'manage_data.php';
include 'fetch_data.php';
include 'process_form.php';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Staff Scheduling - Monthly View</title>
    <link rel="stylesheet" href="style/roster.css">
    <script>
      // Ensure JavaScript functions are available globally
      function changeMonth(direction) {
        if (typeof window.changeMonth === 'function') {
          window.changeMonth(direction);
        }
      }

      function loadCalendar() {
        if (typeof window.loadCalendar === 'function') {
          window.loadCalendar();
        }
      }
    </script>
</head>
<body>
    <div class="container">
        <nav class="nav">
            <h1 class="logo"><img src="/img/logo.svg" alt="Dashboard Image"></h1>
            <ul>
                <li class="dropdown">
                    <a href="adminhome.php">Admin</a>
                </li>
                <li><a href="roster.php">Roster</a></li>
                <li><a href="logout.php">Logout</a></li>
            </ul>
        </nav>

        <div id="tablet-warning">
            <p><strong>Tablet view not supported, please view website on a laptop or desktop.</strong></p>
        </div>
        <div id="mobile-warning">
            <p><strong>Mobile view not supported, please view website on a laptop or desktop.</strong></p>
        </div>

        <div class="roster">
            <h1>Staff Scheduling - Monthly View</h1>

            <!-- Date Selector -->
            <div class="date-selector">
                <button type="button" onclick="changeMonth(-1)">Previous Month</button>
                <span id="currentMonthYear">August 2024</span>
                <button type="button" onclick="changeMonth(1)">Next Month</button>
            </div>

            <!-- Staff Selector -->
            <div class="staff-selector">
                <label for="staff">Select Staff Member:</label>
                <select id="staff" onchange="loadCalendar()">
                    <option value="1">John Doe</option>
                    <option value="2">Jane Smith</option>
                    <option value="3">Mark Johnson</option>
                </select>
            </div>

            <!-- Calendar Container -->
            <div class="calendar-container">
                <div class="calendar-grid" id="calendarGrid">
                    <!-- Day Headers -->
                    <div class="day-header">Sunday</div>
                    <div class="day-header">Monday</div>
                    <div class="day-header">Tuesday</div>
                    <div class="day-header">Wednesday</div>
                    <div class="day-header">Thursday</div>
                    <div class="day-header">Friday</div>
                    <div class="day-header">Saturday</div>

                    <!-- Calendar Days -->
                    <!-- Dynamically generated by JavaScript -->
                </div>
            </div>
        </div>

        <!-- Appointment Modal -->
        <div id="appointment-modal" class="modal">
            <div class="modal-content">
                <span class="close">&times;</span>
                <h2>Appointment Details</h2>
                <form id="appointment-form">
                    <!-- Form fields for appointment details -->
                    <label for="appointment-date">Date:</label>
                    <input type="date" id="appointment-date" name="appointment-date" required>
                    
                    <label for="appointment-time">Time:</label>
                    <input type="time" id="appointment-time" name="appointment-time" required>
                    
                    <label for="appointment-details">Details:</label>
                    <textarea id="appointment-details" name="appointment-details" rows="4" required></textarea>
                    
                    <button type="submit">Save Appointment</button>
                </form>
            </div>
        </div>
    </div>
    <script src="js/roster.js"></script> <!-- Link to your JavaScript file -->
</body>
</html>
